In [1]:
# Python program to convert
# numpy array to image

# import required libraries
import numpy as np
from PIL import Image as im

# define a main function
def main():

	# create a numpy array from scratch
	# using arange function.
	# 1024x720 = 737280 is the amount
	# of pixels.
	# np.uint8 is a data type containing
	# numbers ranging from 0 to 255
	# and no non-negative integers
	array = np.arange(0, 737280, 1, np.uint8)
	
	# check type of array
	print(type(array))
	
	# our array will be of width
	# 737280 pixels That means it
	# will be a long dark line
	print(array.shape)
	
	# Reshape the array into a
	# familiar resoluition
	array = np.reshape(array, (1024, 720))
	
	# show the shape of the array
	print(array.shape)

	# show the array
	print(array)
	
	# creating image object of
	# above array
	data = im.fromarray(array)
	
	# saving the final output
	# as a PNG file
	data.save('gfg_dummy_pic.png')

In [3]:
main()

<class 'numpy.ndarray'>
(737280,)
(1024, 720)
[[  0   1   2 ... 205 206 207]
 [208 209 210 ... 157 158 159]
 [160 161 162 ... 109 110 111]
 ...
 [144 145 146 ...  93  94  95]
 [ 96  97  98 ...  45  46  47]
 [ 48  49  50 ... 253 254 255]]


In [8]:
nen = im.open('4.jpeg')

In [9]:
nen_array = np.asarray(nen, dtype='float32')

In [10]:
norm = np.linalg.norm(nen_array)

In [11]:
nen_array = nen_array/norm

In [13]:
nen_array[0][0]

array([3.5570294e-05, 6.0469500e-04, 7.9871475e-04], dtype=float32)

In [14]:
for x in range(len(nen_array)):
    for y in range(len(nen_array[x])):
        for z in range(3):
            
            if nen_array[x][y][z]%2 == 0:
                nen_array[x][y][z] = nen_array[x][y][z]/4
            else:
                nen_array[x][y][z] = ((6*nen_array[x][y][z])+1)

In [15]:
nen_array = np.reshape(nen_array,(2160,1280))

In [16]:
import matplotlib.pyplot as plt



In [36]:
nen_array = (nen_array * 255).astype(np.uint8,'K')
data = im.fromarray(np.uint8(plt.cm.gist_earth(nen_array)*255))

In [42]:
data.save('nen123.png')

In [44]:
plt.imsave('yay123.png', nen_array, cmap='Greys')